name: Harden Node Alpine

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 2 * * *' # Rebuild nightly
  workflow_dispatch:

permissions:
  actions: read
  packages: write # For publishing to registry
  id-token: write # For signing image

jobs:
  harden:
    runs-on: ubuntu-latest
    outputs:
      image: docker.io/proskemax/node-alpine-hardened:latest
      digest: ${{ steps.image_digest.outputs.IMAGE_DIGEST }}
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image and SBOM
        run: |
          docker buildx bake --push --sbom=true --provenance=false

      - name: Scan image
        uses: docker/scout-action@v1
        with:
          command: cves
          image: docker.io/proskemax/node-alpine-hardened:latest
          only-severities: critical,high,medium,low

      - uses: sigstore/cosign-installer@v3

      - name: Sign image
        env:
          COSIGN_EXPERIMENTAL: "1"
        run: |
          cosign sign --yes --recursive --oidc-issuer https://token.actions.githubusercontent.com docker.io/proskemax/node-alpine-hardened:latest

      - name: Display SBOM & provenance
        run: |
          docker buildx imagetools inspect docker.io/proskemax/node-alpine-hardened:latest
      - name: Output image digest
        id: image_digest
        run: |
          echo "IMAGE_DIGEST=$(docker buildx imagetools inspect docker.io/proskemax/node-alpine-hardened:latest --format '{{json .Digest}}' | tr -d '\"')" >> $GITHUB_OUTPUT

  # Top level required for workflow isolation 
  provenance:
    needs: harden
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_container-based_slsa3.yml@v2.0.0
    with:
      image: ${{ needs.harden.outputs.image }}
      digest: ${{ needs.harden.outputs.digest }}
      builder-image: docker.io/docker/buildx-bin:latest
      builder-digest: sha256:71923cc78f99c462c8578ed270f079c1c234dd70e17913e25e838e4a1721b769
    secrets:
      registry-username: ${{ secrets.DOCKERHUB_USERNAME }}
      registry-password: ${{ secrets.DOCKERHUB_TOKEN }}