name: Harden Node Alpine

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 2 * * *' # Rebuild nightly
  workflow_dispatch:

jobs:
  harden:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    outputs:
      image: docker.io/proskemax/node-alpine-hardened:latest
      digest: ${{ steps.image_digest.outputs.IMAGE_DIGEST }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image and SBOM (no provenance)
        run: |
          docker buildx bake --push --sbom=true --provenance=false

      - name: Scan image
        uses: docker/scout-action@v1
        with:
          command: cves
          image: docker.io/proskemax/node-alpine-hardened:latest
          only-severities: critical,high,medium,low

      - uses: sigstore/cosign-installer@v3

      - name: Sign image
        env:
          COSIGN_EXPERIMENTAL: "1"
        run: |
          cosign sign --yes --recursive --oidc-issuer https://token.actions.githubusercontent.com docker.io/proskemax/node-alpine-hardened:latest

      - id: image_digest
        run: |
          echo "IMAGE_DIGEST=$(docker buildx imagetools inspect docker.io/proskemax/node-alpine-hardened:latest --format '{{json .Digest}}' | tr -d '\"')" >> $GITHUB_OUTPUT


  # Top level required for workflow isolation 
  provenance:
    needs: harden
    permissions:
      id-token: write
      contents: read
      actions: read
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@v2.1.0
    # We just need the image verified, not built
    with:
      image: docker.io/proskemax/node-alpine-hardened
      digest: ${{ needs.harden.outputs.digest }}
    secrets:
      registry-username: ${{ secrets.DOCKERHUB_USERNAME }}
      registry-password: ${{ secrets.DOCKERHUB_TOKEN }}