name: Harden Node Alpine

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 2 * * *' # Rebuild nightly

jobs:
  harden:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: maxproske
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image with SBOM and provenance
        run: |
          docker buildx bake

      - name: Scan image
        uses: docker/scout-action@v1
        with:
          command: cves
          image: docker.io/proskemax/node-alpine-hardened:latest
          only-severities: critical,high,medium,low

      - uses: sigstore/cosign-installer@v3

      - name: Sign image
        env:
          COSIGN_EXPERIMENTAL: "1"
        run: |
          cosign sign --yes --recursive --oidc-issuer https://token.actions.githubusercontent.com docker.io/proskemax/node-alpine-hardened:latest

      - name: Display SBOM & provenance
        run: |
          docker buildx imagetools inspect docker.io/proskemax/node-alpine-hardened:latest 