name: Decode Out Artifact

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  decode:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    outputs:
      image: docker.io/proskemax/slsa3-cv:latest
      digest: ${{ steps.build.outputs.digest }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push decode image
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          target: decode
          push: true
          tags: docker.io/proskemax/slsa3-cv:latest
          sbom: false
          provenance: mode=max
      - uses: sigstore/cosign-installer@v3
      - name: Sign decode image
        env:
          COSIGN_EXPERIMENTAL: "1"
        run: |
          cosign sign --yes --recursive \
            --oidc-issuer https://token.actions.githubusercontent.com \
            docker.io/proskemax/slsa3-cv:latest

  decode-provenance:
    needs: decode
    permissions:
      contents: read
      actions: read
      id-token: write
      packages: write
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@v2.1.0
    with:
      image: docker.io/proskemax/slsa3-cv
      digest: ${{ needs.decode.outputs.digest }}
    secrets:
      registry-username: ${{ secrets.DOCKERHUB_USERNAME }}
      registry-password: ${{ secrets.DOCKERHUB_TOKEN }} 